- name: Generate configuration from template
  ansible.builtin.template:
    src: router_configurations.j2
    dest: config.txt

- name: Apply configuration to the router
  arista.eos.eos_config:
    src: templates/config.txt
