- name: Generate configuration from template
  ansible.builtin.template:
    src: templates/router_configurations.j2
    dest: templates/config.txt

- name: Apply configuration to the router
  arista.eos.eos_config:
    src: templates/config.txt
