- name: Add VLANs
  gather_facts: false
  hosts: all
  tasks:
    - name: Add VLANs
      arista.eos.eos_vlans:
        config:
          - vlan_id: 10
            state: active
        state: merged
